apiVersion: v1
kind: Service
metadata:
  name: budget-ingest-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: budget-ingest-api
  ports:
    - port: {{ .Values.ingestApi.port }}
      targetPort: {{ .Values.ingestApi.port }}
