apiVersion: v1
kind: Secret
metadata:
  name: ingest-api-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.ingestApi.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
