apiVersion: v1
kind: Service
metadata:
  name: budget-manager-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: budget-manager-api
  ports:
    - port: {{ .Values.managerApi.port }}
      targetPort: {{ .Values.managerApi.port }}
